# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clients_info_pb2 as clients__info__pb2


class ClientsInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPremium = channel.unary_unary(
                '/clients.info.ClientsInfo/SetPremium',
                request_serializer=clients__info__pb2.ReqUpdToFP.SerializeToString,
                response_deserializer=clients__info__pb2.RespGeneric.FromString,
                )


class ClientsInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetPremium(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientsInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPremium': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPremium,
                    request_deserializer=clients__info__pb2.ReqUpdToFP.FromString,
                    response_serializer=clients__info__pb2.RespGeneric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clients.info.ClientsInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientsInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetPremium(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clients.info.ClientsInfo/SetPremium',
            clients__info__pb2.ReqUpdToFP.SerializeToString,
            clients__info__pb2.RespGeneric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
