# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clients_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lients_info.proto\x12\x0c\x63lients.info\"\xb9\x02\n\nReqUpdToFP\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x12\n\npremium_id\x18\x02 \x01(\x05\x12\x12\n\nexpires_at\x18\x03 \x01(\t\x12\x14\n\x0cpurchased_at\x18\x04 \x01(\t\x12\x12\n\nauto_renew\x18\x05 \x01(\x08\x12\x1b\n\x13previous_premium_id\x18\x06 \x01(\x05\x12\x1d\n\x15previous_purchased_at\x18\x07 \x01(\t\x12\x1b\n\x13previous_expires_at\x18\x08 \x01(\t\x12\x0e\n\x06period\x18\t \x01(\t\x12\x10\n\x08upd_from\x18\n \x01(\t\x12\r\n\x05\x65mail\x18\x0b \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x0c \x01(\t\x12*\n\x07geo_loc\x18\r \x01(\x0b\x32\x19.clients.info.Coordinates\"2\n\x0b\x43oordinates\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\".\n\x0bRespGeneric\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2R\n\x0b\x43lientsInfo\x12\x43\n\nSetPremium\x12\x18.clients.info.ReqUpdToFP\x1a\x19.clients.info.RespGeneric\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clients_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUPDTOFP']._serialized_start=37
  _globals['_REQUPDTOFP']._serialized_end=350
  _globals['_COORDINATES']._serialized_start=352
  _globals['_COORDINATES']._serialized_end=402
  _globals['_RESPGENERIC']._serialized_start=404
  _globals['_RESPGENERIC']._serialized_end=450
  _globals['_CLIENTSINFO']._serialized_start=452
  _globals['_CLIENTSINFO']._serialized_end=534
# @@protoc_insertion_point(module_scope)
