# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import treasury_pb2 as treasury__pb2


class TreasuryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InstructPayment = channel.unary_unary(
                '/treasury.Treasury/InstructPayment',
                request_serializer=treasury__pb2.ReqInstructPayment.SerializeToString,
                response_deserializer=treasury__pb2.RespGeneric.FromString,
                )


class TreasuryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InstructPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreasuryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InstructPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.InstructPayment,
                    request_deserializer=treasury__pb2.ReqInstructPayment.FromString,
                    response_serializer=treasury__pb2.RespGeneric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'treasury.Treasury', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Treasury(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InstructPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/treasury.Treasury/InstructPayment',
            treasury__pb2.ReqInstructPayment.SerializeToString,
            treasury__pb2.RespGeneric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
